pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
      - GOPATH=/drone
    commands:
      - make vet
      - make build
      - make test
  docker:
    storage_driver: overlay
    repo: msuterski/drone-terraform
    tag: [ "latest" ]
    when:
      branch: release/0.4.2
      event: push

plugin:
  name: Terraform
  desc: Execute Terraform plan and apply
  type: deploy
  image: msuterski/drone-terraform
  labels:
    - terraform
